name: CI

on:
  pull_request:
    branches: master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: |
          npm ci
          npm run tsc
          npm run webpack
